### ISSUE TITLE
未来是否会考虑增加“崩坏：星穹铁道”有关的成就管理功能

### ISSUE THREAD

**Issue by IThinkIGottaGo** [YuehaiTeam/herta.space#1]
谢谢🙏🏻

**Comment by xytoki** [comment]
已经有在考虑

**Comment by xytoki** [comment]
但是形式不太确定，不知道是开新站好还是做一个栏目好

**Comment by IThinkIGottaGo** [comment]
> 但是形式不太确定，不知道是开新站好还是做一个栏目好

好的，谢谢🙏🏻

不过我个人感觉可以先开一个栏目，后面有好的域名了，或者好的ui设计了可以再分离出去，再给两边分别加个互相跳转banner或者图标之类的就好😉

**Comment by jiongjiongJOJO** [comment]
> 但是形式不太确定，不知道是开新站好还是做一个栏目好

新开一个域名吧，用cocogoat引流过去，毕竟原神的这个域名跟崩铁毫不相关

而且新开网站的话，账号系统也更好做吧，不然cocogoat的代码估计也得改一些（看不懂vue，猜的）

**Comment by xytoki** [comment]
新开的话账号、后端之类的也得复制一份过去，不过主要还是我对新站叫啥没啥想法，数据都拉下来了

**Comment by IThinkIGottaGo** [comment]
> 新开的话账号、后端之类的也得复制一份过去，不过主要还是我对新站叫啥没啥想法，数据都拉下来了

哈哈，要不叫可可利亚吧，也是 coco 开头的😄

**Comment by jiongjiongJOJO** [comment]
> > 新开的话账号、后端之类的也得复制一份过去，不过主要还是我对新站叫啥没啥想法，数据都拉下来了
> 
> 哈哈，要不叫可可利亚吧，也是 coco 开头的😄

可以（cocoly？）
建议在cocogoat首页搞个征集活动，哈哈哈哈哈😂😂

**Comment by xytoki** [comment]
我把这个issue地址挂公告了，可以一起想想😂

**Comment by lyfc633** [comment]
cocoyaya？可可利亚和布洛丽亚（鸭鸭）

**Comment by jiongjiongJOJO** [comment]
> cocoyaya？可可利亚和布洛丽亚（鸭鸭）

中文不太好取名

**Comment by jiongjiongJOJO** [comment]
> 新开的话账号、后端之类的也得复制一份过去，不过主要还是我对新站叫啥没啥想法，数据都拉下来了

可以先开一个cocogoat的二级域名当做测试，取名什么的暂时不关注，成就系统确实还是刚需，后面确定了取名再注册域名迁移过去

**Comment by fastboot-rec** [comment]
cocosr，coco+StarRail缩写

**Comment by jiongjiongJOJO** [comment]
中文：卡夫卡
英文：cofco

**Comment by suyy2002** [comment]
可帕cocopom

**Comment by Xyyaua** [comment]
###### _~真就喜欢啥写啥~_

**CN: 可瓦罗（或许能直接用 史瓦罗，像 cocogoat 一样 （?
EN: cocovarog**

描述: 史瓦罗~都差不多是个ChatGPT 9了~，肯定能整吧（至少是个人工智能

**Comment by youtuhan** [comment]
期待!果然会出！泰裤辣！👏👏👏

**Comment by Mz-xiaofeng** [comment]
~~怎么看前面的建议都是coco开头，有什么讲究吗~~
我觉得可以直接用**穷观阵**这个名字，毕竟也算是用来穷观所有成就

**Comment by repokx** [comment]
总结下？
1. 下划一个子域，把hsr的成就系统塞进去
    + 实施起来有难度，vue看不懂，账号系统和同步难做。
    + 可能的话... 把hsr的信息添加到椰羊的账号里一块儿同步？
2. 新域名，新网址，新账号
    + 基本完全独立，原转崩的可以从椰羊引流过去
    + 建起来比较麻烦，申请新域名也不是很便宜（吗？）
    + 可能没多少流量（不清楚实际情况怎样，莫名感觉hsr玩不长... 虽然现阶段很有意思...）

然后，我的建议？
新域名的话，感觉可以往coco上凑，也倒不是说非得这样搞。就是这样很容易让人能联想到隔壁cocogoat，用cocogoat的人也能很顺理成章的认为这俩是一家的，会很放心

*可可利亚？可克拉拉？可刻鸭鸭？~~可可萝？~~*
*Cocolia? Coclara? Cocoronya? ~~Kokoro?~~*
什么才能成为崩铁的代名词，让玩崩铁的人一眼就能看出是崩铁，还能引人会心一笑。
最好能引用些好笑的梗，椰羊就很好...
崩铁梗太多反而找不到这样的会心一笑的了...

强凑coco略显牵强的话，抛开coco，也许可以从黑塔身上入手？
*Herta Analysis?*
（~~黑塔的小脚丫，小小的香香的，哎嘿嘿嘿~~）

集思广益好评

**Comment by xytoki** [comment]
打算开新站直接复制全套过去，后端已经复制好了，数据也准备了，前端还在弄，因为希望尽可能复用椰羊的组件，所以需要对椰羊也做一点修改，新站估计下周才会出来。识别会慢一点，等网站稳定了再来

**Comment by jiongjiongJOJO** [comment]
> 打算开新站直接复制全套过去，后端已经复制好了，数据也准备了，前端还在弄，因为希望尽可能复用椰羊的组件，所以需要对椰羊也做一点修改，新站估计下周才会出来。识别会慢一点，等网站稳定了再来

暂时不需要cv，我直接手动点已完成的成就😂

**Comment by xytoki** [comment]
域名目前拿下了herta.space（黑塔空间站）和pompom.wiki（帕姆wiki），反正新注册不贵，下周看心情挑一个把新站上线过去x
做新站是考虑到以后两边需求会不太一样，到时候因为复用太多改起来太麻烦就不好了

**Comment by jiongjiongJOJO** [comment]
> 域名目前拿下了herta.space（黑塔空间站）和pompom.wiki（帕姆wiki），反正新注册不贵，下周看心情挑一个把新站上线过去x
> 做新站是考虑到以后两边需求会不太一样，到时候因为复用太多改起来太麻烦就不好了

搞一个帕姆空间站（bushi

**Comment by jiongjiongJOJO** [comment]
虽然已经注册了域名，但还是想说
派姆
paim

Paimon和Pom-Pom的结合体🤗

**Comment by MegaRange** [comment]
既然原神侧是用了椰羊这个非常不重要但是很有代表性的名字，
那铁道这边不如直接用：
### ”**冷面小青龙**“


![图片](https://github.com/YuehaiTeam/cocogoat/assets/8201842/67f41174-122b-4757-bbfc-504d29d5672b)

_编辑：丹恒作为智库的管理员，对于这个工具的主题来讲，别说还挺合适。_

**Comment by xytoki** [comment]
> 既然原神侧是用了椰羊这个非常不重要但是很有代表性的名字， 那铁道这边不如直接用：
> 
> ### ”**冷面小青龙**“
> ![图片](https://user-images.githubusercontent.com/8201842/240976760-67f41174-122b-4757-bbfc-504d29d5672b.png)
> 
> _编辑：丹恒作为智库的管理员，对于这个工具的主题来讲，别说还挺合适。_

有英文域名推荐吗（x
（怎么感觉要变成域名收集计划了

**Comment by xytoki** [comment]
反正代码还在写，到时候随机选一个上线x

**Comment by MegaRange** [comment]
> 

根据“冷面小青龙”的英文版对应名号“Cold Dragon Young”，结合相关信息，以下是比较合适的域名猜想：

- dragon.young
- dragon.dan
- danheng.data

_以上文本使用MegaBot AI辅助系统生成，敬请注意_

**Comment by Andrea-Chenjia-Pan** [comment]
最近越来越希望崩铁的成就检测能上线了，自己筛选太难了。。。期待大佬的成果！感谢大佬的付出！

**Comment by xytoki** [comment]
半成品已经出来了，预计月底之前完善正式上线，想试的可以先上x
https://herta.space

**Comment by tntruik** [comment]
@xytoki 网站已经试了，「本地化」挺好的就是仍有许多问题。
1.部分任务分类名称未翻译。
2.将鼠标悬停在左上角（成就数/获取星琼数[icon]）中弹出内容仍是「原石」
目前就发现这些问题。

**Comment by xytoki** [comment]
收到，没翻译那个是已知，“原石”是真忘记了马上回去全局替换，还有一些同步、缺样式、任务名字未解析之类的问题和一些优化会在月底前一起处理。

**Comment by jiongjiongJOJO** [comment]
> 收到，没翻译那个是已知，“原石”是真忘记了马上回去全局替换，还有一些同步、缺样式、任务名字未解析之类的问题和一些优化会在月底前一起处理。

慢慢来，能用就行😜😜😜

**Comment by xytoki** [comment]
目前版本已经基本可用，因为在部分重构，晚些开源

**Comment by Haocen2004** [comment]
https://herta.space/manifest.json 这个文件挂了（
会自动指向index.html(?) 总之网站打不开.jpg

**Comment by xytoki** [comment]
> https://herta.space/manifest.json 这个文件挂了（ 会自动指向index.html(?) 总之网站打不开.jpg

这个文件不影响任何使用。

**Comment by Haocen2004** [comment]
> > https://herta.space/manifest.json 这个文件挂了（ 会自动指向index.html(?) 总之网站打不开.jpg
> 
> 这个文件不影响任何使用。

所以现在网站卡在 列车即将到站 是正常维护状态对吗

**Comment by chokjay** [comment]
与你同行的回忆成就中：
雄虺蓁蓁 1.0
云骑之友 1.2
这两个成就应该是二选一
做丹枢支线任务就会给`雄虺蓁蓁 1.0`
不做丹枢支线任务就会给`云骑之友 1.2`

**Comment by Jolin0** [comment]
这个得手动钩吗？没找到像椰羊读屏识别这样的？这得怎么操作，手动太麻烦。

**Comment by Jolin0** [comment]
又重新开了吗
