### ISSUE TITLE
2.0成就问题

### ISSUE THREAD

**Issue by washipss** [YuehaiTeam/herta.space#15]
二选一成就被各自单独列出来了
向着明亮的那方和他也在这阳光下长大，为柯柯娜支线的分支成就。

**Comment by autumnqiuji** [comment]
好像就这一个有问题，请问与你同行的回忆 最终应该是201个吗？

**Comment by washipss** [comment]
> 好像就这一个有问题，请问与你同行的回忆 最终应该是201个吗？

我现在的成就数是200个，加上一个我还未完成的收集77个艾迪恩代币的幸运条纹人成就，总成就数应当为201。

**Comment by lucienshawls** [comment]
#16 相同问题

**Comment by lucienshawls** [comment]
并未成功修复：#20 #22 #23 #25
