### ISSUE TITLE
2.0的成就有一个问题

### ISSUE THREAD

**Issue by 020323** [YuehaiTeam/herta.space#16]
![IMG_20240216_223020](https://github.com/YuehaiTeam/herta.space/assets/122003220/fd25d7e0-377a-479a-a5f7-bbda95b8265f)
这两个成就应该是二选一的，2.0版本的总成就数应该是689，但是因为这个错误导致网页上显示总成就数为690

**Comment by lucienshawls** [comment]
#15 相同问题

**Comment by lucienshawls** [comment]
并未成功修复：#20 #22 #23 #25
