### ISSUE TITLE
云同步无法添加账户，无法登录

### ISSUE THREAD

**Issue by roronoa-chen** [YuehaiTeam/herta.space#17]
系统
Windows 10 企业版 22H2

浏览器
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36

多次尝试从邮箱接收的链接进行登录，提示成功但返回后都并未登录，刷新无效

**Comment by roronoa-chen** [comment]
求求了求求了救救孩子吧，，换了各种浏览器都不行，邮件中的地址显示登录成功，再次进入页面依然不行，浏览器看接口报跨域，，同网络手机ios安卓都可以使用，但是手机上看不到完整的描述啊！！！我好难受。。。

**Comment by xytoki** [comment]
暂时无法复现，麻烦关闭设置-错误报告和统计后截图下报错内容吧

**Comment by roronoa-chen** [comment]
> 暂时无法复现，麻烦关闭设置-错误报告和统计后截图下报错内容吧

1.发送邮箱验证码后控制台就一直报错接口404：
<img width="1920" alt="1" src="https://github.com/YuehaiTeam/herta.space/assets/50428336/b6019770-195c-4770-94e5-b001d337c4ba">

2.进入邮件连接，显示登录完成：
<img width="1920" alt="2" src="https://github.com/YuehaiTeam/herta.space/assets/50428336/5c86d818-0f4e-495f-a1de-eb59b779c2ef">

3.再次输入网址进入仍然没有登录完成，账号未同步：
<img width="1920" alt="3" src="https://github.com/YuehaiTeam/herta.space/assets/50428336/1eba650d-3bff-44a9-8f56-c6cb60a0f8e4">
<img width="1920" alt="4" src="https://github.com/YuehaiTeam/herta.space/assets/50428336/cebc5618-d87f-4cce-ab30-01c7c47989ac">

**Comment by xytoki** [comment]
在邮件里点击链接提示登录成功后，原来的网页是什么状态？

**Comment by roronoa-chen** [comment]
> 在邮件里点击链接提示登录成功后，原来的网页是什么状态？

看到你回复后再次尝试才成功
win系统上是在原页面输入输入链接地址访问的，覆盖了原页面。。。。。看到你的回复后新开页面输入邮件连接后，再返回原先页面发现登录成功了😂。。。。
（mac、ios、安卓都是覆盖原页面的都没有问题😂😂😂😂😂）
