### ISSUE TITLE
2.2新成就所属分支有较多偏差（【通往群星的轨道】和【与你同行的回忆】）

### ISSUE THREAD

**Issue by Cross-Winds** [YuehaiTeam/herta.space#37]
RT
1. 目前【通往群星的轨道】中，【终结技是永远的真诚】（※在「巨星巅峰战」中击败银枝）和【真诚是永远的终结技】（※在「巨星巅峰战」中说服银枝）很可能属于同一个多选一分支，但目前两个成就是独立分开的；
2. 目前【与你同行的回忆】中，大量2.2新增成就被错误配置进同一个多选一分支中。

**Comment by kazuha-YUE** [comment]
我也发现了这个问题

**Comment by pale-s1gh** [comment]
是的，在【与你同行的回忆】中：
```
把历史装进瓶子、糖浆药水的故事、黄金与机械…表？、只是一道行走的影子
```
以及
```
前有绝景，所以悲伤、箱梯游戏、等待戈多、可以坐一下午、爱遇之城
```
共9个相互独立的成就，被错误地配置为以上两个分支。

**Comment by xytoki** [comment]
已调整，基于任务自动判断分支成就看起来问题不小……
