### ISSUE TITLE
感谢更新崩铁成就系统 发现2个小问题

### ISSUE THREAD

**Issue by zongziren** [YuehaiTeam/herta.space#8]
铁齿铜牙 1.4
聆听小小西衍的节目
说学逗唱 1.4
聆听小往小来的节目

这2个不是分支成就 设置为分支了

胜利，然后是再见 1.4
在尘埃落定后归还{TEXTJOIN#54}
结束，然后是开始 1.4
在尘埃落定后留下{TEXTJOIN#54}

这2个是分支成就 没有设置为分支

**Comment by xytoki** [comment]
已修复，然后这两个文案问题会后面处理
